<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmployeesSeeder extends Seeder
{
    public function run(): void
    {
        $employees = [
            [
                'id' => 1,
                'id_karyawan' => '1501.01.0001',
                'first_name' => 'Krishnan',
                'last_name' => 'Suppaiah',
                'email' => 'kris@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'kris'
            ],
            [
                'id' => 2,
                'id_karyawan' => '1908.01.0021',
                'first_name' => 'Denizia',
                'last_name' => 'Rizky',
                'email' => 'denizia@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'denizia'
            ],
            [
                'id' => 3,
                'id_karyawan' => '2308.01.0079',
                'first_name' => 'Aprillia',
                'last_name' => 'Frinanda Setiawan',
                'email' => 'frinanda@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'frinanda'
            ],
            [
                'id' => 4,
                'id_karyawan' => '2211.01.0067',
                'first_name' => 'Ine',
                'last_name' => 'Suwartiningsih Wulandari',
                'email' => 'ine@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'ine'
            ],
            [
                'id' => 5,
                'id_karyawan' => '1910.01.0023',
                'first_name' => 'Made',
                'last_name' => 'Witrianti',
                'email' => 'made@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'made'
            ],
            [
                'id' => 6,
                'id_karyawan' => '2604.01.0122',
                'first_name' => 'Danny',
                'last_name' => 'Indah Agustine',
                'email' => 'danny@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'danny'
            ],
            [
                'id' => 7,
                'id_karyawan' => '2308.01.0079',
                'first_name' => 'Aurensia',
                'last_name' => 'Putri Azzahra',
                'email' => 'aurensia@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'aurensia'
            ],
            [
                'id' => 8,
                'id_karyawan' => '2505.01.0110',
                'first_name' => 'Fadilah',
                'last_name' => 'Rizki Solikhah',
                'email' => 'dila@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'dila'
            ],
            [
                'id' => 9,
                'id_karyawan' => '1908.01.0022',
                'first_name' => 'Ari',
                'last_name' => 'Kurnia Partomo',
                'email' => 'ari@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'ari'
            ],
            [
                'id' => 10,
                'id_karyawan' => '2208.01.0059',
                'first_name' => 'Adellia',
                'last_name' => 'Rachma Hardini',
                'email' => 'adellia@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'adellia'
            ],
            [
                'id' => 11,
                'id_karyawan' => '2402.01.0089',
                'first_name' => 'Nur',
                'last_name' => 'Hafidah Lula Kamal',
                'email' => 'vivi@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'vivi'
            ],
            [
                'id' => 12,
                'id_karyawan' => '2507.01.0111',
                'first_name' => 'Eviyanti',
                'last_name' => 'Zakariyah',
                'email' => 'evi@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'evi'
            ],
            [
                'id' => 13,
                'id_karyawan' => '2407.01.0101',
                'first_name' => 'Cavilla',
                'last_name' => 'Anggie Falljack',
                'email' => 'cavilla@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'cavilla'
            ],
            [
                'id' => 14,
                'id_karyawan' => 13006060,
                'first_name' => 'Nuril',
                'last_name' => 'Lailatus',
                'email' => 'nuril@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'nuril'
            ],
            [
                'id' => 15,
                'id_karyawan' => '2511.01.0120',
                'first_name' => 'Nadya',
                'last_name' => 'Nur Khotimah',
                'email' => 'nadya@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'nadya'
            ],
            [
                'id' => 16,
                'id_karyawan' => 13006883,
                'first_name' => 'Axanda',
                'last_name' => 'Bilqis Prameswari',
                'email' => 'bilqis@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'bilqis'
            ],
            [
                'id' => 17,
                'id_karyawan' => '2608.01.0124',
                'first_name' => 'Novita',
                'last_name' => 'Cahyaning Permata Sari',
                'email' => '',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'novita'
            ],
            [
                'id' => 18,
                'id_karyawan' => '1302.01.0006',
                'first_name' => 'Nita',
                'last_name' => 'Agusningtias',
                'email' => 'nita@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'nita'
            ],
            [
                'id' => 19,
                'id_karyawan' => '2409.01.0104',
                'first_name' => 'Anita',
                'last_name' => 'Andini',
                'email' => 'andini@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'andini'
            ],
            [
                'id' => 20,
                'id_karyawan' => '2508.01.0112',
                'first_name' => 'Ayu',
                'last_name' => 'Salsabila Fitriannisa',
                'email' => 'sabil@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'sabil'
            ],
            [
                'id' => 21,
                'id_karyawan' => '1505.01.0009',
                'first_name' => 'Anggie',
                'last_name' => 'Satria Armanda Putra',
                'email' => 'anggie@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'anggie'
            ],
            [
                'id' => 22,
                'id_karyawan' => '2509.01.0115',
                'first_name' => 'Ahmad',
                'last_name' => 'Nafi Budianto',
                'email' => 'nafi@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'nafi'
            ],
            [
                'id' => 23,
                'id_karyawan' => '2607.01.0123',
                'first_name' => 'Nuzul',
                'last_name' => 'Nur Fadillah',
                'email' => 'nuzul@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$UE5LZVFiNkFvd3cxcGhSdg$k0Zk50ZPazBz3LgHLf3pRQVl4NuScJEg8s4VHltcqQA',
                'deleted_at' => null,
                'profile_photo_path' => '',
                'created_at' => null,
                'updated_at' => '2026-08-24 14:57:36',
                'username' => 'nuzul'
            ],
            [
                'id' => 24,
                'id_karyawan' => '2403.01.0090',
                'first_name' => 'Atim',
                'last_name' => 'Ainul Hidayah',
                'email' => 'atim@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'atim'
            ],
            [
                'id' => 25,
                'id_karyawan' => '1603.02.0073',
                'first_name' => 'Khalimatul',
                'last_name' => 'Jannah',
                'email' => 'ima@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'ima'
            ],
            [
                'id' => 26,
                'id_karyawan' => '2103.01.0044',
                'first_name' => 'Ninda',
                'last_name' => 'Intan Pratiwi',
                'email' => 'ninda@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'ninda'
            ],
            [
                'id' => 27,
                'id_karyawan' => '2407.01.0100',
                'first_name' => 'Reza',
                'last_name' => 'Fadilah Ardhani',
                'email' => 'reza@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'reza'
            ],
            [
                'id' => 28,
                'id_karyawan' => '2407.01.0099',
                'first_name' => 'Dwi',
                'last_name' => 'Rahmawati',
                'email' => 'rahma@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'rahma'
            ],
            [
                'id' => 29,
                'id_karyawan' => '2407.01.0098',
                'first_name' => 'Sania',
                'last_name' => 'Rahmawati',
                'email' => 'sania@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'sania'
            ],
            [
                'id' => 30,
                'id_karyawan' => '2504.01.0107',
                'first_name' => 'Cindy',
                'last_name' => 'Wiranti',
                'email' => 'cindy@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'cindy'
            ],
            [
                'id' => 31,
                'id_karyawan' => 13002639,
                'first_name' => 'Fina',
                'last_name' => 'Suroiya',
                'email' => '',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => null
            ],
            [
                'id' => 32,
                'id_karyawan' => 13007005,
                'first_name' => 'Sulvi',
                'last_name' => 'Puspita Sari',
                'email' => '',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'sulvi'
            ],
            [
                'id' => 33,
                'id_karyawan' => '2210.01.0064',
                'first_name' => 'Rahmat',
                'last_name' => 'Akbar',
                'email' => 'rahmat@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'rahmat'
            ],
            [
                'id' => 34,
                'id_karyawan' => 13002964,
                'first_name' => 'Nela',
                'last_name' => 'Rosita',
                'email' => 'nela@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'nela'
            ],
            [
                'id' => 35,
                'id_karyawan' => '2401.01.0085',
                'first_name' => 'Kizah',
                'last_name' => 'Musdalifah',
                'email' => 'kizah@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'kizah'
            ],
            [
                'id' => 36,
                'id_karyawan' => '2404.01.0093',
                'first_name' => 'Theresia',
                'last_name' => 'Arcell Arinjani Marsudi',
                'email' => 'theresia@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'theresia'
            ],
            [
                'id' => 37,
                'id_karyawan' => '2406.01.0095',
                'first_name' => 'Fidya',
                'last_name' => 'Ainun Nisa',
                'email' => 'fidya@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'fidya'
            ],
            [
                'id' => 38,
                'id_karyawan' => '0602.02.0007',
                'first_name' => 'Binti',
                'last_name' => 'Suryani',
                'email' => 'binte@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'binte'
            ],
            [
                'id' => 39,
                'id_karyawan' => '1810.02.0112',
                'first_name' => 'Febiana',
                'last_name' => 'Intan Wulandari',
                'email' => 'intan@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'intan'
            ],
            [
                'id' => 40,
                'id_karyawan' => '2510.01.0118',
                'first_name' => 'Destyanola',
                'last_name' => 'Ayu Setyaningrum',
                'email' => 'nola@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'nola'
            ],
            [
                'id' => 41,
                'id_karyawan' => '2504.01.0109',
                'first_name' => 'Carendy',
                'last_name' => 'Indrawan',
                'email' => 'carendy@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'carendy'
            ],
            [
                'id' => 42,
                'id_karyawan' => 13006850,
                'first_name' => 'Elyana',
                'last_name' => 'Lestari',
                'email' => 'eliana@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'eliana'
            ],
            [
                'id' => 43,
                'id_karyawan' => 13003882,
                'first_name' => 'Amanda',
                'last_name' => 'Nuril',
                'email' => '',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'nuril'
            ],
            [
                'id' => 44,
                'id_karyawan' => '2510.01.0117',
                'first_name' => 'Wahyu',
                'last_name' => 'Arum Mustikasari',
                'email' => 'maintenance@supasurya.com',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'arum'
            ],
            [
                'id' => 45,
                'id_karyawan' => '0307.02.0004',
                'first_name' => 'Nurudin',
                'last_name' => '',
                'email' => '',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'nurudin'
            ],
            [
                'id' => 46,
                'id_karyawan' => '1702.02.0076',
                'first_name' => 'Eko',
                'last_name' => 'Setiya Budi',
                'email' => '',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'eko'
            ],
            [
                'id' => 47,
                'id_karyawan' => 13004208,
                'first_name' => 'Supras',
                'last_name' => 'Setyo',
                'email' => '',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'supras'
            ],
            [
                'id' => 48,
                'id_karyawan' => 13003685,
                'first_name' => 'Mochamad',
                'last_name' => 'Ilham Anafis',
                'email' => '',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'ilham'
            ],
            [
                'id' => 49,
                'id_karyawan' => 13003993,
                'first_name' => 'Riki',
                'last_name' => 'Doni Saputra',
                'email' => '',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'riki'
            ],
            [
                'id' => 50,
                'id_karyawan' => 13006008,
                'first_name' => 'Denni',
                'last_name' => 'Siswardana',
                'email' => '',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'denni'
            ],
            [
                'id' => 51,
                'id_karyawan' => 13006605,
                'first_name' => 'Muhammad',
                'last_name' => 'Syarif Hidayatullah',
                'email' => '',
                'no_telepon' => null,
                'no_telepon_alt' => null,
                'birth_place' => null,
                'birth_date' => null,
                'marital_status' => 'Belum Menikah',
                'nik' => null,
                'address_ktp' => null,
                'address_residence' => null,
                'hire_date' => '2026-08-12',
                'is_active' => true,
                'password' => '$argon2id$v=19$m=65536,t=4,p=1$emdQaWhTUU0wZmtYUGhLLg$E72RGUSO3BEv+kwfJh8ddO7dGhqnPr+GlEz+YtRbFVc',
                'deleted_at' => null,
                'profile_photo_path' => null,
                'created_at' => null,
                'updated_at' => null,
                'username' => 'syarif'
            ]
        ];

        DB::table('employees')->insert($employees);

        // Karena data di atas membawa ID eksplisit 1-51, sinkronkan sequence PostgreSQL
        // agar insert berikutnya mendapatkan ID sesudah ID terbesar.
        if (DB::getDriverName() === 'pgsql') {
            DB::statement("SELECT setval(pg_get_serial_sequence('employees', 'id'), COALESCE((SELECT MAX(id) FROM employees), 1), true)");
        }
    }
}
