<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function () {
            DB::statement('TRUNCATE TABLE "core"."products" RESTART IDENTITY CASCADE');

            DB::unprepared(<<<'SQL'
INSERT INTO "core"."products" ("id", "name", "name_indonesian", "deleted_at") VALUES
	(1, 'Allspice', 'Allspice', NULL),
	(2, 'Almond', 'Almond', NULL),
	(3, 'Andaliman Pepper', 'Andaliman', NULL),
	(4, 'Baked Cashew Garlic', 'Kacang Mete Panggang Bawang Putih', NULL),
	(5, 'Baked Cashew Honey', 'Kacang Mete Panggang Madu', NULL),
	(6, 'Baked Cashew Ori', 'Kacang Mete Panggang Original', NULL),
	(7, 'Baked Cashew Salted', 'Kacang Mete Panggang Asin', NULL),
	(8, 'Basil', 'Kemangi', NULL),
	(9, 'Bay Leaf', 'Daun Salam', NULL),
	(10, 'Black Cardamom', 'Kapulaga Hitam', NULL),
	(11, 'Black Cumin', 'Jintan Hitam', NULL),
	(12, 'Black Garlic', 'Bawang Putih Hitam', NULL),
	(13, 'Black Ginger', 'Jahe Hitam', NULL),
	(14, 'Black Lime', 'Jeruk Limau Hitam', NULL),
	(15, 'Black Mustard', 'Mustard Hitam', NULL),
	(16, 'Black Pepper', 'Lada Hitam', NULL),
	(17, 'Black Sesame', 'Wijen Hitam', NULL),
	(18, 'Black Turmeric', 'Kunyit Hitam', NULL),
	(19, 'Brazil Nuts', 'Kacang Brasil', NULL),
	(20, 'Candlenut', 'Kemiri', NULL),
	(21, 'Caplak Chili', 'Cabai Caplak', NULL),
	(22, 'Caraway', 'Jintan Karawai', NULL),
	(23, 'Cardamom', 'Kapulaga', NULL),
	(24, 'Cashew', 'Kacang Mete', NULL),
	(25, 'Cayenne Pepper', 'Cabai Cayenne', NULL),
	(26, 'Celery Leaf', 'Daun Seledri', NULL),
	(27, 'Celery Seeds', 'Biji Seledri', NULL),
	(28, 'Chestnut', 'Kacang Kastanye', NULL),
	(29, 'Chick Peas', 'Kacang Arab', NULL),
	(30, 'Chili', 'Cabai', NULL),
	(31, 'Chipotle Chili', 'Cabai Chipotle', NULL),
	(32, 'Chives', 'Kucai', NULL),
	(33, 'Cilantro Leaves', 'Daun Ketumbar', NULL),
	(34, 'Cinnamon', 'Kayu Manis', NULL),
	(35, 'Clove', 'Cengkeh', NULL),
	(36, 'Coriander', 'Ketumbar', NULL),
	(37, 'Cubeb', 'Kemukus', NULL),
	(38, 'Cumin', 'Jintan', NULL),
	(39, 'Curcuma', 'Temulawak', NULL),
	(40, 'Curly Green Chili', 'Cabai Keriting Hijau', NULL),
	(41, 'Curly Red Chili', 'Cabai Keriting Merah', NULL),
	(42, 'Curry Leaf', 'Daun Kari', NULL),
	(43, 'Dill', 'Daun Dill', NULL),
	(44, 'Fennel', 'Adas', NULL),
	(45, 'Fenugreek', 'Kelabat', NULL),
	(46, 'Galangal', 'Lengkuas', NULL),
	(47, 'Garlic', 'Bawang Putih', NULL),
	(48, 'Gendot Chili', 'Cabai Gendot', NULL),
	(49, 'Ginger', 'Jahe', NULL),
	(50, 'Green Cardamom', 'Kapulaga Hijau', NULL),
	(51, 'Green Chili', 'Cabai Hijau', NULL),
	(52, 'Habanero Chili', 'Cabai Habanero', NULL),
	(53, 'Hazelnut', 'Kacang Hazelnut', NULL),
	(54, 'Hot Chili', 'Cabai Pedas', NULL),
	(55, 'Jablay Chili', 'Cabai Jablay', NULL),
	(56, 'Jalapeno Chili', 'Cabai Jalapeno', NULL),
	(57, 'Java Almond', 'Kenari Jawa', NULL),
	(58, 'Kaffir Lime', 'Jeruk Purut', NULL),
	(59, 'Kluwek', 'Kluwek', NULL),
	(60, 'Laurel', 'Daun Laurel', NULL),
	(61, 'Leek', 'Daun Bawang', NULL),
	(62, 'Lemongrass', 'Serai', NULL),
	(63, 'Lime', 'Jeruk Nipis', NULL),
	(64, 'Long Pepper', 'Cabai Jawa', NULL),
	(65, 'Macadamia', 'Kacang Macadamia', NULL),
	(66, 'Mace', 'Bunga Pala', NULL),
	(67, 'Marjoram', 'Marjoram', NULL),
	(68, 'Nutmeg', 'Pala', NULL),
	(69, 'Onion', 'Bawang Bombay', NULL),
	(70, 'Oregano', 'Oregano', NULL),
	(71, 'Pandan Leaf', 'Daun Pandan', NULL),
	(72, 'Paprika Chili', 'Cabai Paprika', NULL),
	(73, 'Parsley', 'Peterseli', NULL),
	(74, 'Pea', 'Kacang Polong', NULL),
	(75, 'Peanuts', 'Kacang Tanah', NULL),
	(76, 'Pecan', 'Kacang Pecan', NULL),
	(77, 'Pepper', 'Lada', NULL),
	(78, 'Pine Kernels', 'Kacang Pinus', NULL),
	(79, 'Pistachios', 'Kacang Pistachio', NULL),
	(80, 'Raw Cashew', 'Kacang Mete Mentah', NULL),
	(81, 'Red Ginger', 'Jahe Merah', NULL),
	(82, 'Red Onion', 'Bawang Merah', NULL),
	(83, 'Roasted Cashew', 'Kacang Mete Sangrai', NULL),
	(84, 'Roasted Garlic', 'Bawang Putih Sangrai', NULL),
	(85, 'Roasted Onion', 'Bawang Bombay Sangrai', NULL),
	(86, 'Roasted Shallot', 'Bawang Merah Sangrai', NULL),
	(87, 'Rosemary', 'Rosemary', NULL),
	(88, 'Sage', 'Sage', NULL),
	(89, 'Seasoning Briyani', 'Bumbu Briyani', NULL),
	(90, 'Seasoning Cajun', 'Bumbu Cajun', NULL),
	(91, 'Seasoning Chimichurri', 'Bumbu Chimichurri', NULL),
	(92, 'Seasoning Chinese Five Spices', 'Bumbu Lima Rempah Tiongkok', NULL),
	(93, 'Seasoning Curry', 'Bumbu Kari', NULL),
	(94, 'Seasoning Empon - Empon', 'Bumbu Empon-Empon', NULL),
	(95, 'Seasoning Fish Curry', 'Bumbu Kari Ikan', NULL),
	(96, 'Seasoning Garam Masala', 'Bumbu Garam Masala', NULL),
	(97, 'Seasoning Italian', 'Bumbu Italia', NULL),
	(98, 'Seasoning Kebuli', 'Bumbu Kebuli', NULL),
	(99, 'Seasoning Madras Curry', 'Bumbu Kari Madras', NULL),
	(100, 'Seasoning Mala', 'Bumbu Mala', NULL),
	(101, 'Seasoning Meat Curry', 'Bumbu Kari Daging', NULL),
	(102, 'Seasoning Mixed Spices', 'Bumbu Rempah Campuran', NULL),
	(103, 'Seasoning Padang Chicken', 'Bumbu Ayam Padang', NULL),
	(104, 'Seasoning Padang Fish', 'Bumbu Ikan Padang', NULL),
	(105, 'Seasoning Padang Meat', 'Bumbu Daging Padang', NULL),
	(106, 'Seasoning Powder', 'Bumbu Bubuk', NULL),
	(107, 'Seasoning Rendang', 'Bumbu Rendang', NULL),
	(108, 'Seasoning Seafood', 'Bumbu Seafood', NULL),
	(109, 'Seasoning Seblak', 'Bumbu Seblak', NULL),
	(110, 'Seasoning Spekuk', 'Bumbu Spekuk', NULL),
	(111, 'Seasoning Taco', 'Bumbu Taco', NULL),
	(112, 'Shallot', 'Bawang Merah', NULL),
	(113, 'Sichuan Pepper', 'Lada Sichuan', NULL),
	(114, 'Smoked Paprika Chili', 'Paprika Asap', NULL),
	(115, 'Soy Bean', 'Kedelai', NULL),
	(116, 'Spicy Ginger', 'Jahe Pedas', NULL),
	(117, 'Star Anise', 'Bunga Lawang / Pekak', NULL),
	(118, 'Sumac', 'Sumac', NULL),
	(119, 'Sunflower Seeds', 'Biji Bunga Matahari', NULL),
	(120, 'Sweet Paprika', 'Paprika Manis', NULL),
	(121, 'Tamarind', 'Asam Jawa', NULL),
	(122, 'Tarragon', 'Tarragon', NULL),
	(123, 'Thyme', 'Thyme', NULL),
	(124, 'Toasted Candlenut', 'Kemiri Sangrai', NULL),
	(125, 'Toasted Coriander', 'Ketumbar Sangrai', NULL),
	(126, 'Toasted Cumin', 'Jintan Sangrai', NULL),
	(127, 'Toasted Garlic', 'Bawang Putih Sangrai', NULL),
	(128, 'Toasted Onion', 'Bawang Bombay Sangrai', NULL),
	(129, 'Toasted Shallot', 'Bawang Merah Sangrai', NULL),
	(130, 'Tom Yam', 'Tom Yam', NULL),
	(131, 'Turmeric', 'Kunyit', NULL),
	(132, 'Turmeric Leaf', 'Daun Kunyit', NULL),
	(133, 'TW Chili', 'Cabai TW', NULL),
	(134, 'Walnuts', 'Kacang Walnut', NULL),
	(135, 'White Onion', 'Bawang Bombay Putih', NULL),
	(136, 'White Pepper', 'Lada Putih', NULL),
	(137, 'White Sesame', 'Wijen Putih', NULL),
	(138, 'Yellow Mustard', 'Mustard Kuning', NULL),
	(139, 'Zedoary', 'Temu Putih', NULL),
	(140, 'Chili Stem', 'Tangkai Cabai', NULL);
SQL
            );

            DB::statement(
                'SELECT setval(pg_get_serial_sequence(\'core.products\', \'id\'), COALESCE((SELECT MAX(id) FROM "core"."products"), 1), true)'
            );
        });
    }
}
